version: 1

formatters:
  detailed:
    class: logging.Formatter
    format: '[%(filename)s:%(lineno)d] %(asctime)s %(name)-15s %(levelname)-8s %(message)s'
#    format: '[%(pathname)s:%(lineno)d] %(asctime)s %(name)-15s %(levelname)-8s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log

loggers:
  scrape.py.app:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

  uvicorn:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

root:
  level: DEBUG
  handlers: [ console ]

coloredlogs:
  level: DEBUG
  fmt: '[%(pathname)s:%(lineno)d] %(asctime)s %(name)-15s %(levelname)-8s %(message)s'
  #  fmt: '[%(filename)s:%(lineno)d] %(asctime)s %(name)-15s %(levelname)-8s %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
